"""
Exports the currently seeded database to database/dummy_data.sql in
MySQL-compatible form, so the exact same demo data can be loaded into
MySQL with:  mysql -u root -p < database/dummy_data.sql  (after schema.sql)

Run after seed.py:  python export_sql.py
"""
import datetime
import os

from app import create_app
from extensions import db

TABLES = [
    "roles", "departments", "users", "subjects", "teachers", "teacher_subjects",
    "students", "parents", "parent_student", "attendance", "ia_marks",
    "assignments", "semester_results", "backlogs", "ml_predictions",
    "notifications",
]


def literal(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (datetime.datetime, datetime.date)):
        return "'" + value.strftime("%Y-%m-%d %H:%M:%S") + "'"
    s = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def main():
    app = create_app()
    out_path = os.path.join(os.path.dirname(__file__), "..", "database", "dummy_data.sql")
    lines = [
        "-- CAMPS demo dataset (generated by backend/export_sql.py)",
        "-- Load order: schema.sql first, then this file.",
        "USE academic_monitoring;",
        "",
        "SET FOREIGN_KEY_CHECKS = 0;",
    ]
    with app.app_context():
        conn = db.engine.raw_connection()
        cur = conn.cursor()
        for table in TABLES:
            cur.execute(f"SELECT * FROM {table}")
            rows = cur.fetchall()
            cols = [d[0] for d in cur.description]
            lines.append(f"TRUNCATE TABLE {table};")
            for row in rows:
                values = ", ".join(literal(v) for v in row)
                lines.append(
                    f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({values});"
                )
            lines.append("")
        conn.close()
    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    lines.append("")

    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {os.path.abspath(out_path)} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
