import express from 'express'; import cors from 'cors'; import jwt from 'jsonwebtoken'; import multer from 'multer'; import XLSX from 'xlsx'; import fs from 'fs'; import path from 'path';
const app=express(), PORT=process.env.PORT||5174, SECRET=process.env.JWT_SECRET||'campuscore-dev-secret';
app.use(cors()); app.use(express.json()); const upload=multer({dest:'uploads/'});
const students=[
 {usn:'4PM23CS001',name:'Rahul Kumar',gender:'Male',dob:'2005-03-18',bloodGroup:'B+',department:'Computer Science & Engineering',semester:5,section:'A',admissionYear:2023,email:'rahul.kumar@pes.edu',phone:'9876543210',address:'Banashankari, Bengaluru',fatherName:'Suresh Kumar',motherName:'Lakshmi Kumar',parentPhone:'9845012345',parentEmail:'suresh.kumar@email.com',cgpa:8.7,previousSgpa:8.5,backlogs:0,attendance:91,ia1:28,ia2:26,assignment:18,achievements:'Smart India Hackathon finalist',remarks:'Consistent performance. Keep up the good work.',photo:null},
 {usn:'4PM23CS002',name:'Ananya Sharma',gender:'Female',dob:'2005-08-10',bloodGroup:'O+',department:'Computer Science & Engineering',semester:5,section:'A',admissionYear:2023,email:'ananya.sharma@pes.edu',phone:'9811122233',address:'Indiranagar, Bengaluru',fatherName:'Rajesh Sharma',motherName:'Neeta Sharma',parentPhone:'9811100000',parentEmail:'rajesh.sharma@email.com',cgpa:9.2,previousSgpa:9.0,backlogs:0,attendance:96,ia1:29,ia2:30,assignment:19,achievements:'Department merit scholar',remarks:'Excellent academic work.',photo:null},
 {usn:'4PM23CS003',name:'Vikram Reddy',gender:'Male',dob:'2005-11-02',bloodGroup:'A+',department:'Computer Science & Engineering',semester:5,section:'A',admissionYear:2023,email:'vikram.reddy@pes.edu',phone:'9900011223',address:'Jayanagar, Bengaluru',fatherName:'Ramesh Reddy',motherName:'Suma Reddy',parentPhone:'9900099999',parentEmail:'ramesh.reddy@email.com',cgpa:6.1,previousSgpa:6.4,backlogs:2,attendance:68,ia1:16,ia2:14,assignment:11,achievements:'',remarks:'Attendance and IA performance need immediate attention.',photo:null},
 {usn:'4PM23CS004',name:'Meera Nair',gender:'Female',dob:'2005-06-25',bloodGroup:'AB+',department:'Computer Science & Engineering',semester:5,section:'B',admissionYear:2023,email:'meera.nair@pes.edu',phone:'9988776655',address:'Whitefield, Bengaluru',fatherName:'Arun Nair',motherName:'Priya Nair',parentPhone:'9988700000',parentEmail:'arun.nair@email.com',cgpa:7.8,previousSgpa:7.6,backlogs:0,attendance:84,ia1:23,ia2:24,assignment:16,achievements:'NSS volunteer',remarks:'',photo:null}
];
let messages=[{id:1,to:'4PM23CS003',from:'Dr. Priya Nair',subject:'Low Attendance Warning',body:'Your attendance is below the required threshold. Please attend all remaining classes.',createdAt:'2026-08-20',read:false},{id:2,to:'4PM23CS001',from:'Dr. Priya Nair',subject:'Assignment Reminder',body:'Please submit the Data Structures assignment by Friday.',createdAt:'2026-08-21',read:true}];
let announcements=[{id:1,title:'Mid-semester Examination Schedule',body:'The mid-semester examinations begin on September 12. Please check the timetable.',scope:'College',department:'All',semester:'All',date:'2026-08-21'},{id:2,title:'Semester 5 Project Review',body:'First project review is scheduled for August 29 in the department seminar hall.',scope:'Semester',department:'Computer Science & Engineering',semester:5,date:'2026-08-22'}];
const risk=s=>{let score=s.attendance<75||s.backlogs>0||s.ia1<18||s.ia2<18?'High':s.attendance<85||s.cgpa<7?'Medium':'Low';let p=score==='Low'?92:score==='Medium'?74:48; return {risk:score,pass_probability:p,history:[{date:'2026-08-23',risk:score,pass_probability:p},{date:'2026-07-12',risk:score==='High'?'Medium':'Low',pass_probability:p-5}]}}
function token(user){return jwt.sign(user,SECRET,{expiresIn:'8h'})} function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{return res.status(401).json({error:'Unauthorized'})}}
app.get('/api/departments',(q,r)=>r.json(['Computer Science & Engineering','Electronics & Communication','Mechanical Engineering','Civil Engineering','MBA']));
app.post('/api/auth/login',(req,res)=>{const {role,username}=req.body; let u={role,name:role==='Teacher'?'Dr. Priya Nair':role==='Admin'?'System Administrator':role==='Parent'?'Suresh Kumar':'Rahul Kumar',username:username||'demo'}; if(role==='Student'&&username) {const s=students.find(x=>x.usn===username);if(s)u={...u,name:s.name,usn:s.usn}} if(role==='Parent')u.usn='4PM23CS001';res.json({token:token(u),user:u})});
app.post('/api/auth/logout',auth,(q,r)=>r.json({message:'Logged out successfully'}));
app.get('/api/students',auth,(req,res)=>{let a=students; if(req.query.semester)a=a.filter(s=>s.semester==req.query.semester);res.json(a.map(s=>({...s,prediction:risk(s)})))});
app.post('/api/students',auth,(req,res)=>{if(students.some(s=>s.usn===req.body.usn))return res.status(409).json({error:'Duplicate USN'}); const required=['usn','name','email','semester'];let missing=required.filter(k=>!req.body[k]);if(missing.length)return res.status(400).json({error:`Required: ${missing.join(', ')}`});if(!/^\S+@\S+\.\S+$/.test(req.body.email))return res.status(400).json({error:'Invalid email'});students.push({...req.body,semester:+req.body.semester,attendance:+req.body.attendance||0,ia1:+req.body.ia1||0,ia2:+req.body.ia2||0,assignment:+req.body.assignment||0,cgpa:+req.body.cgpa||0,previousSgpa:+req.body.previousSgpa||0,backlogs:+req.body.backlogs||0});res.status(201).json(req.body)});
app.get('/api/students/:usn',auth,(req,res)=>{let s=students.find(x=>x.usn===req.params.usn);s?res.json({...s,prediction:risk(s),messages:messages.filter(m=>m.to===s.usn),announcements:announcements.filter(a=>a.scope==='College'||a.semester==='All'||a.semester===s.semester)}):res.sendStatus(404)});
app.put('/api/students/:usn',auth,(req,res)=>{let i=students.findIndex(x=>x.usn===req.params.usn);if(i<0)return res.sendStatus(404);students[i]={...students[i],...req.body};res.json(students[i])});app.delete('/api/students/:usn',auth,(req,res)=>{let i=students.findIndex(x=>x.usn===req.params.usn);if(i<0)return res.sendStatus(404);students.splice(i,1);res.sendStatus(204)});
app.post('/api/students/:usn/metrics',auth,(req,res)=>{let s=students.find(x=>x.usn===req.params.usn);if(!s)return res.sendStatus(404);Object.assign(s,req.body);res.json({...s,prediction:risk(s)})}); app.get('/api/students/:usn/prediction',auth,(q,r)=>{let s=students.find(x=>x.usn===q.params.usn);s?r.json(risk(s)):r.sendStatus(404)});
app.get('/api/messages',auth,(q,r)=>r.json(messages.filter(m=>!q.query.usn||m.to===q.query.usn))); app.post('/api/messages',auth,(q,r)=>{let m={id:Date.now(),from:q.user.name,createdAt:new Date().toISOString().slice(0,10),read:false,...q.body};messages.unshift(m);r.status(201).json(m)});app.patch('/api/messages/:id/read',auth,(q,r)=>{let m=messages.find(x=>x.id==q.params.id);if(m)m.read=true;r.json(m)});
app.get('/api/announcements',auth,(q,r)=>r.json(announcements));app.post('/api/announcements',auth,(q,r)=>{let a={id:Date.now(),date:new Date().toISOString().slice(0,10),...q.body};announcements.unshift(a);r.status(201).json(a)});
app.post('/api/students/import/preview',auth,upload.single('file'),(req,res)=>{try{let wb=XLSX.readFile(req.file.path), rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});fs.unlinkSync(req.file.path);let valid=[],errors=[];rows.forEach((x,i)=>{let e=[];if(!x.USN)e.push('Empty USN');if(students.some(s=>s.usn===x.USN))e.push('Duplicate USN');if(!x.Email||!/^\S+@\S+\.\S+$/.test(x.Email))e.push('Invalid email');if(![1,2,3,4,5,6,7,8].includes(+x.Semester))e.push('Invalid semester');(e.length?errors:valid).push(e.length?{row:i+2,data:x,errors:e}:x)});res.json({valid,errors})}catch(e){res.status(400).json({error:'Unable to read file'})}});
app.listen(PORT,'0.0.0.0',()=>console.log(`API on ${PORT}`));
