import { useNavigate } from 'react-router-dom'
import { FiArrowLeft, FiCheck, FiLogOut, FiSettings, FiShield, FiUser } from 'react-icons/fi'
import { useAuth } from '../context/AuthContext'
import { Brand } from './Landing'

export default function TeacherAccount({ mode = 'profile' }) {
  const navigate = useNavigate()
  const { user, logout } = useAuth()
  const signOut = async () => { await logout(); navigate('/login', { replace: true }) }
  const profile = mode === 'profile'
  return <main className="teacher-account-page"><header className="teacher-account-header"><Brand light /><div className="teacher-account-header-actions"><button type="button" onClick={() => navigate('/teacher/semesters')}><FiArrowLeft /> Back to workspace</button><button type="button" onClick={signOut} aria-label="Sign out"><FiLogOut /></button></div></header><section className="teacher-account-content"><div className="teacher-account-heading"><span className="teacher-account-eyebrow"><FiShield /> Teacher account</span><h1>{profile ? 'Profile' : 'Settings'}</h1><p>{profile ? 'Your identity and department access details.' : 'Your CAMPS workspace preferences and permissions.'}</p></div><section className="teacher-account-card"><div className="teacher-account-card-head"><span className="teacher-account-avatar"><FiUser /></span><div><h2>{user.name}</h2><p>{user.designation || 'Teacher'} · {user.department} department</p></div><span className="teacher-account-status"><i /> Active</span></div>{profile ? <div className="teacher-account-details"><div><span>Full name</span><strong>{user.name}</strong></div><div><span>Role</span><strong>Teacher</strong></div><div><span>Email address</span><strong>{user.email || 'Not recorded'}</strong></div><div><span>Department</span><strong>{user.department}</strong></div><div><span>Designation</span><strong>{user.designation || 'Faculty'}</strong></div><div><span>Access</span><strong>Department-scoped</strong></div></div> : <div className="teacher-settings-list"><div><span><FiShield /> Department scope</span><strong>{user.department} only</strong></div><div><span><FiUser /> Session identity</span><strong>JWT-secured teacher account</strong></div><div><span><FiCheck /> Data visibility</span><strong>Semester → section → student</strong></div></div>}<div className="teacher-account-actions"><button className="button-ghost" type="button" onClick={() => navigate('/teacher/semesters')}><FiArrowLeft /> Return to semesters</button><button className="button-primary" type="button" onClick={() => navigate(profile ? '/teacher/settings' : '/teacher/profile')}><FiSettings /> {profile ? 'Open settings' : 'View profile'}</button></div></section></section></main>
}
